travis:
  secure:
    BINSTAR_TOKEN: lNx1BKACfHRkMT1EOm9iWMnFF27gml6OcTBnLcg2AS8VbZfmnjUAlHWIkcvv2SWiLsWI1JTNbTn5T5YK741knD3//UV+YVten1tPxxU7JOEabg2xXjmkkFiM3K28NuxaWHjzio5jOrAAhBiTw1O1gONihR8HRekMGV5LdzE5vkWjihcSfcZkLhgWvzQ5ypLIJ4Ij9rUnUV6cHdx/JyFneA+xqH7Hev2Ndy+/StRj/uA+aVgLY37wvURsfW4BbTzJ6fnyvXUyvViB1xA2hTf5A1/lC+BvXMShkkWFVqfpzmAmbBE/kAwC+HO5nIAp1IBJEH7PXjUmYXLPQ/3ufl8AyjGgbAPAHS6JIDOiglHOuAcs17EL26biMi3J6kduYsmtK2xy9Ok9QUTaNF3FTpWfpl/lj7too9uBziEXpoT/Nmxh1GNuASwrSCuU3MyhE+Pzgk9z1heb68w3RGedhdVA/EDoK3tc1fyKQITfF1j+sJCO/4TVtRw/7AFb517/NvTn7TOS3ucc5ODhRXTt/biGqnc2MiYSUJfcOEIo/K2kGi+PkVmSxxq6D6/E+y0J7aXcPGTsW5ErheU7MU0oZemt0IopbsoEiXm8xkgcO7+5XVsmAEezYXCL38sQ1JXE4GReClqXgBQB/ofisLI2IhL5CQ0AIXU5FMT5bdngYKeVZlk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
