travis:
  secure:
    BINSTAR_TOKEN: re1G3dwNJ0C1RikDzbKGZcA/fWBIIOd1gpZ3k9Pp1nn1izZ4mcPXRQcvuyxNid6tu/IBD4Y1ylSNjmPZkIxwfgqKAuGWfKdqCJMfjqr5c8V69gnOQ8eUoIFSf5kqvyn0PIjGFPLqvNheuapUWpwdk4ihrRdbzSD6gYLrd/20Ql1edWTB1McrnhR8v4fCc3X4Gs+GfQjNpKyWjaYLB/xpd/PK1xtVRpd2X5C6uys3xjGQlNbcZMFsjUjyoOmuDbHW5A6rHEUY0vn9bmTnMY/ldx5nfsNb/dp6mK8FYpwMl2tPA7b+LBIy8dbGJF2/XEfMn+3yyOqpRAhgCIuI0DU1IA0AOqQhkRomh+VsSIjZd5C0Yn1faBBWfY1f6+1UKf9WZA/9nc58yO9AZucq5oF89Z/70/0Mxv+KyKx8L9d+OZpyyyh9gwaQIxZNldwgKK3AdcsjoSm7n56RzE6eNphL5slVcl5kqG6ucS+RKYERjFB2mHRKb5ewE+HGFoV1k7oMhdjyvZEEt8p/FUFkPtQVVBI8wZniMXWm5ECXY90CUwWxPcdZPsW+WlFqoNrd9fYtshcakMOZx02vDhWKZAqKH/u9BBaBCAa6/bHAMVomfoYU6HiUxL6TCby+maBzM7rlKUtqeMaRdy3ZxxKOcj6EvpoxvCgEL0SM75qxAv30+K0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
