travis:
  secure:
    BINSTAR_TOKEN: aCjn54bZHQgGx4//QI5x/QKlsWnHxFCs0gbJGDgjrYNHwX/yS9g34AHakxbICyNQQRPdWm6cX1KR/QlhxZ6f8BFmvd/22ZbJAPa0JyPqTAAgjv98rizMUobrauRL/oSl724hYBIP/hwiTzeQvUrizaE3COygj7gtE7zkAeHqJyiYJXEUZSCLiwYfW4g4sMyVhLFEIh+ZAvWycSb9DkcuR+7CxAhkS4tw6Z7ZvU29Sssu/Hufa3yuzhpKgQuGBbuO+kjKehLvHf9/72+f/i1h1bAt24l4GqRVeMMacgxJnNa24hg3Im5pplpE3C7RMBG6lmQYSD5pzA9pmbLX04WfQgz/y2rjLhHv6C2Sm+eQqdMPm8FfA8VfCB/b+F+e3JbiKSn53sIFABc+oiZzI/VvIoqsbJg5N3ckizkee/Q/BSBZsjrWyZRUbLHVtljrrd4fpyfIvJV0UA88lkLLU6k6YsdlZAO2n3V+7mluvFM7Pq/OyS5cxFZsfmdVikR+MBun1yD1CvDV4GHkCxGdmfeTLBSUWVi7wn95zSvNxyHo8m1s2+86czAeCnpOEpjADT2RWygLOj2/11JDUYhKlxciroKJ4IYCXy5VvYdapvUvGGIgi8Bx+AOTJ8w+ygGq1Hw1MBV1gnJqU+mOAYKkgPsXjZPHQiaY3WBV620I4lFhtJg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
